### ISSUE TITLE
Rectangular 3d surface

### ISSUE THREAD

**Issue by BlackBlade** [Niekes/d3-3d#1]
Hi, i'm using your library to create a surface with axes. I simply mixed up your examples of the scatterplot  and 3d surface, and everything works fine. I then tried to create a "rectangular" surface/grid with some rows and points per row (N of points per row != N of rows), but failed. I was just wondering if it was possible to create a rectangular grid.

EDIT: i noticed that when you create and render a plane with Nrows > N points per row, the code just breaks, while the vice-versa creates a distoted plane. You can try it by modifying your  3d surface plot parameters.

[Your example](https://bl.ocks.org/niekes/e920c03edd7950578b8a6cded8b5a1a5)

**Comment by Niekes** [comment]
Hey, this is a bug. I will fix this in the next release. Thanks for the hint !

**Comment by MariDani** [comment]
Hi Niekes, I was just wondering when are you planning the next release? Having this bug fixed would be great for me as well. Thanks a lot!

**Comment by Niekes** [comment]
Hey, last month I was in Brazil so I couldn't work on d3-3d. I think the next release will be in February.
