### ISSUE TITLE
PrimitiveTypes() Function is gone missing.  

### ISSUE THREAD

**Issue by fishjd** [Niekes/d3-3d#7]
The example https://bl.ocks.org/niekes/ff4d3c8497d8436d4d8fdb9f0121d12d  uses the function `.primitiveType('LINES');`   This function is not in the current release of d3-3d.js downloaded from https://github.com/Niekes/d3-3d/releases  version 0.0.9 .

**Comment by Niekes** [comment]
This was a first test. Please take a look at the the README. PrimitiveTypes() is now shape()
